FROM runpod/pytorch:1.0.2-cu1281-torch280-ubuntu2404

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1

RUN mkdir -p /scripts

WORKDIR /scripts
COPY scripts/download_models.py /scripts/download_models.py

# Download missing libraries that the script might need
RUN pip install --no-cache-dir tqdm requests

CMD ["python", "/scripts/download_models.py", "/workspace/models"]
